name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  build-test:
    name: Lint ➜ Test ➜ Build ➜ Axe
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test -- --coverage=false

      - name: Build
        run: pnpm build

      - name: Accessibility (Axe CLI)
        run: pnpm ci:axe
